[[pages]]
path = "pages/0_Home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
name = "Combat Log Parser"
is_section = true
icon = "ğŸ“œ"

[[pages]]
path = "pages/2_Apex_Barrier_Analysis.py"
name = "Apex Barrier Analysis"
icon = "ğŸ›¡ï¸"

[[pages]]
path = "pages/3_Player_Info.py"
name = "Player Info"
icon = "ğŸ§‘â€ğŸš€"

[[pages]]
path = "pages/4_Actual_Damage_Pools.py"
name = "Damage Flow by Round"
icon = "ğŸ”€"

[[pages]]
path = "pages/7_Damage_Flow_Sankey.py"
name = "Damage Flow by Battle"
icon = "ğŸŒŠ"

[[pages]]
path = "pages/5_Raw_Damage_Analysis.py"
name = "Raw Damage by Type"
icon = "ğŸ’¥"

[[pages]]
path = "pages/8_Critical_Hit_Analysis.py"
name = "Hits and Crits"
icon = "ğŸ¯"

[[pages]]
path = "pages/6_Officers_and_Tech.py"
name = "Officer & Tech Procs"
icon = "ğŸ§‘"

[[pages]]
path = "pages/9_Settings.py"
name = "Settings"
icon = "âš™ï¸"
