[[pages]]
path = "pages/0_Home.py"
name = "juHmaj"
icon = "ğŸ "

[[pages]]
name = "Defense"
is_section = true
icon = "ğŸ“œ"

[[pages]]
path = "pages/2_Apex_Barrier_Analysis.py"
name = "Apex Barrier Analysis"
icon = "ğŸ›¡ï¸"

[[pages]]
path = "pages/2_Observed_Mitigation.py"
name = "Observed Mitigation"
icon = "ğŸ§®"

[[pages]]
path = "pages/3_Observed_Shield_Mitigation.py"
name = "Observed Shield Mitigation"
icon = "ğŸ›¡ï¸"


[[pages]]
name = "Flow"
is_section = true
icon = "ğŸ“œ"

[[pages]]
path = "pages/4_Damage_Flow_By_Round.py"
name = "Damage Flow by Round"
icon = "ğŸ”€"

[[pages]]
path = "pages/7_Damage_Flow_Sankey.py"
name = "Damage Flow by Battle"
icon = "ğŸŒŠ"


[[pages]]
name = "Offense"
is_section = true
icon = "ğŸ“œ"

[[pages]]
path = "pages/10_Attacker_Shot_Heatmaps.py"
name = "Shot Heatmaps"
icon = "ğŸ”¥"

[[pages]]
path = "pages/5_Raw_Damage_Analysis.py"
name = "Raw Damage by Type"
icon = "ğŸ’¥"

[[pages]]
path = "pages/8_Critical_Hit_Analysis.py"
name = "Hits and Crits"
icon = "ğŸ¯"

[[pages]]
path = "pages/8a_Crit_Chance_Trends.py"
name = "Crit Chance Trends"
icon = "ğŸ“ˆ"

[[pages]]
name = "Officers and Tech"
is_section = true
icon = "ğŸ“œ"

[[pages]]
path = "pages/6_Proc_Frequency_by_Round.py"
name = "Proc Frequency by Round"
icon = "ğŸ§‘"

[[pages]]
path = "pages/7_Proc_Summary_for_Battle.py"
name = "Proc Summary for Battle"
icon = "ğŸ“Š"

[[pages]]
name = "Other"
is_section = true
icon = "ğŸ“œ"

[[pages]]
path = "pages/12_Log_File_Explorer.py"
name = "Log File Explorer"
icon = "ğŸ§¾"

[[pages]]
path = "pages/11_Builder.py"
name = "Share Build"
icon = "ğŸ“¤"

[[pages]]
path = "pages/9_Settings.py"
name = "Settings"
icon = "âš™ï¸"
